package com.telesure.digitalamendments;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class contactDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("workNumber")
	private java.lang.String workNumber;

	@org.kie.api.definition.type.Label("contactNumber")
	private java.lang.String contactNumber;

	@org.kie.api.definition.type.Label("email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "errorMessage")
	private java.lang.String errorMessage;

	public contactDetails() {
	}

	public java.lang.String getWorkNumber() {
		return this.workNumber;
	}

	public void setWorkNumber(java.lang.String workNumber) {
		this.workNumber = workNumber;
	}

	public java.lang.String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(java.lang.String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public contactDetails(java.lang.String workNumber,
			java.lang.String contactNumber, java.lang.String email,
			java.lang.String errorMessage) {
		this.workNumber = workNumber;
		this.contactNumber = contactNumber;
		this.email = email;
		this.errorMessage = errorMessage;
	}

}