package com.telesure.digitalamendments;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testobj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("msgs")
	private java.util.List<java.lang.String> msgs;

	@org.kie.api.definition.type.Label("age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label("error")
	private java.util.List<com.telesure.digitalamendments.error> error;

	public testobj() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.util.List<java.lang.String> getMsgs() {
		return this.msgs;
	}

	public void setMsgs(java.util.List<java.lang.String> msgs) {
		this.msgs = msgs;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.util.List<com.telesure.digitalamendments.error> getError() {
		return this.error;
	}

	public void setError(
			java.util.List<com.telesure.digitalamendments.error> error) {
		this.error = error;
	}

	public testobj(java.lang.String name,
			java.util.List<java.lang.String> msgs, java.lang.Integer age,
			java.util.List<com.telesure.digitalamendments.error> error) {
		this.name = name;
		this.msgs = msgs;
		this.age = age;
		this.error = error;
	}

}