package com.telesure.digitalamendments;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class personalDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("firstName")
	private java.lang.String firstName;
	@org.kie.api.definition.type.Label("lastName")
	private java.lang.String lastName;
	@org.kie.api.definition.type.Label("errorMessage")
	private java.lang.String errorMessage;

	@org.kie.api.definition.type.Label("title")
	private java.lang.String title;

	@org.kie.api.definition.type.Label(value = "errors")
	private java.util.List<java.lang.String> errors;

	public personalDetails() {
	}

	public java.lang.String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(java.lang.String firstName) {
		this.firstName = firstName;
	}

	public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.util.List<java.lang.String> getErrors() {
		return this.errors;
	}

	public void setErrors(java.util.List<java.lang.String> errors) {
		this.errors = errors;
	}

	public personalDetails(java.lang.String firstName,
			java.lang.String lastName, java.lang.String errorMessage,
			java.lang.String title, java.util.List<java.lang.String> errors) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.errorMessage = errorMessage;
		this.title = title;
		this.errors = errors;
	}

}